export const Ping = [
    {
        des: "Don't Ping Before Scanning - [ -Pn ]",
        value: "-Pn",
        tooltip: "Don't check if targets are up before scanning them. Scan every target listed.",
        input: false,
        egInput: null,
    },
    {
        des: "ICMP Ping --- [ -PE ]",
        value: "-PE",
        tooltip: "Send an ICMP echo request(ping) probe to see if targets are up.",
        input: false,
        egInput: null,
    },
    {
        des: "ICMP Timestamp Request --- [ PP ]",
        value: "-PP",
        tooltip: "Send an ICMP timestamp probe to see if targets are up.",
        input: false,
        egInput: null,
    },
    {
        des: "ICMP Netmask Request --- [ -PM ]",
        value: "-PM",
        tooltip: "Send an ICMP address mask request probe to see if targets are up.",
        input: false,
        egInput: null,
    },
    {
        des: "ACK Ping --- [ -PA ]",
        value: "-PA",
        tooltip: "Send one or more ACK probes to see if targets are up. Give a list of ports or leave the argument blank to use a default port.",
        input: true,
        egInput: "23, 55, 80",
    },
    {
        des: "SYN Ping --- [ -PS ]",
        value: "-PS",
        tooltip: "Send one or more SYN probes to see if targets are up. Give a list of ports or leave the argument blank to use a default port.",
        input: true,
        egInput: "23, 55, 80",
    },
    {
        des: "UDP Probes --- [ -PU ]",
        value: "-PU",
        tooltip: "Send one or more UDP probes to see if targets are up. Give a list of ports or leave the argument blank to use a default port.",
        input: true,
        egInput: "100, 31338",
    },
    {
        des: "IPProto Probes --- [ -PO ]",
        value: "-PO",
        tooltip: "Send one or more UDP probes to see if targets are up. Give a list of ports or leave the argument blank to use a default port.",
        input: true,
        egInput: "1, 2, 4",
    },
    {
        des: "SCTP INIT Ping Probes --- [ -PY ]",
        value: "-PY",
        tooltip: "Send one or more UDP probes to see if targets are up. Give a list of ports or leave the argument blank to use a default port.",
        input: true,
        egInput: "20, 80, 179",
    },
]

export const NSE = [
    {
        des: "Don't Ping Before Scanning - [ -Pn ]",
        value: "-Pn",
        tooltip: "Don't check if targets are up before scanning them. Scan every target listed.",
        input: false,
        egInput: null,
    },
    {
        des: "ICMP Ping --- [ -PE ]",
        value: "-PE",
        tooltip: "Send an ICMP echo request(ping) probe to see if targets are up.",
        input: false,
        egInput: null,
    },
    {
        des: "ICMP Timestamp Request --- [ PP ]",
        value: "-PP",
        tooltip: "Send an ICMP timestamp probe to see if targets are up.",
        input: false,
        egInput: null,
    },
    {
        des: "ICMP Netmask Request --- [ -PM ]",
        value: "-PM",
        tooltip: "Send an ICMP address mask request probe to see if targets are up.",
        input: false,
        egInput: null,
    },
    {
        des: "ACK Ping --- [ -PA ]",
        value: "-PA",
        tooltip: "Send one or more ACK probes to see if targets are up. Give a list of ports or leave the argument blank to use a default port.",
        input: true,
        egInput: "23, 55, 80",
    },
    {
        des: "SYN Ping --- [ -PS ]",
        value: "-PS",
        tooltip: "Send one or more SYN probes to see if targets are up. Give a list of ports or leave the argument blank to use a default port.",
        input: true,
        egInput: "23, 55, 80",
    },
    {
        des: "UDP Probes --- [ -PU ]",
        value: "-PU",
        tooltip: "Send one or more UDP probes to see if targets are up. Give a list of ports or leave the argument blank to use a default port.",
        input: true,
        egInput: "100, 31338",
    },
    {
        des: "IPProto Probes --- [ -PO ]",
        value: "-PO",
        tooltip: "Send one or more UDP probes to see if targets are up. Give a list of ports or leave the argument blank to use a default port.",
        input: true,
        egInput: "1, 2, 4",
    },
    {
        des: "SCTP INIT Ping Probes --- [ -PY ]",
        value: "-PY",
        tooltip: "Send one or more UDP probes to see if targets are up. Give a list of ports or leave the argument blank to use a default port.",
        input: true,
        egInput: "20, 80, 179",
    },
]

export const Target = [
    {
        des: "Excluded hosts/networks --- [ --exclude ]",
        value: "--exclude",
        tooltip: "Specifies a comma-sparated list of targets to exclude from the scan.",
        input: true,
        egInput: "scanme.nmap.org",
    },
    {
        des: "Exclusion Files --- [ --excludefile ]",
        value: "--excludefile",
        tooltip: "Specifies a newline-, space-, or tab- delimited file of targets to exclude from the scan.",
        input: true,
        egInput: "exclude_file.txt",
    },
    {
        des: "Port to Scan --- [ -p ]",
        value: "-p",
        tooltip: "This option speceifies which ports you want to scan and overrides the default.",
        input: true,
        egInput: "1-1023, 3389",
    },
    {
        des: "Scan Random Hosts --- [ -iR ]",
        value: "-iR",
        tooltip: "Option to choose targets at random. Tells Nmap how many IPs to generate. 0 is used for a never-ending scan.",
        input: true,
        egInput: "10",
    },
    {
        des: "Fast Scan --- [ -F ]",
        value: "-F",
        tooltip: "Only scan pors named in the nmap-services file which comes with Nmap (or nmap_protocols file for -sO).",
        input: true,
        egInput: "23, 55, 80",
    },
    {
        des: "User Decoys to Hide Identity --- [ -D ]",
        value: "-D",
        tooltip: "Send fake decoy probes from spoofed addresses to hide your own address. Give list of addresses seprarted by commas. Use RND for a random address and ME to et the position of your address.",
        input: true,
        egInput: "{decoy1}, {decoy2}, ME, RND, RND",
    },
    {
        des: "SYN Ping --- [ -S ]",
        value: "-S",
        tooltip: "Specifty the IP address of the interface you wish to send packets through.",
        input: true,
        egInput: "64, 13, 134, 52",
    },
    {
        des: "Set Source Port --- [ --source-port ]",
        value: "--source-port",
        tooltip: "Provide a port number and Nmap will send packets from that port where possible.",
        input: true,
        egInput: "53",
    },
    {
        des: "Set Network Interface --- [ -e ]",
        value: "-PY",
        tooltip: "Tells Nmap what interface to send and receive packet on.",
        input: true,
        egInput: "eth0",
    },
]

export const Source = [
    {
        des: "User Decoys to Hide Identity --- [ -D ]",
        value: "-D",
        tooltip: "Send fake decoy probes from spoofed addresses to hide your own address. Give list of addresses seprarted by commas. Use RND for a random address and ME to et the position of your address.",
        input: true,
        egInput: "{decoy1}, {decoy2}, ME, RND, RND",
    },
    {
        des: "SYN Ping --- [ -S ]",
        value: "-S",
        tooltip: "Specifty the IP address of the interface you wish to send packets through.",
        input: true,
        egInput: "64, 13, 134, 52",
    },
    {
        des: "Set Source Port --- [ --source-port ]",
        value: "--source-port ",
        tooltip: "Provide a port number and Nmap will send packets from that port where possible.",
        input: true,
        egInput: "53",
    },
    {
        des: "Set Network Interface --- [ -e ]",
        value: "-e",
        tooltip: "Send one or more SYN probes to see if targets are up. Give a list of ports or leave the argument blank to use a default port.",
        input: true,
        egInput: "eth0",
    },
]

export const Timing = [
    {
        des: "Max Time to Scan a Target --- [ --host-timeout ]",
        value: "--host-timeout",
        tooltip: "Give up on a host if it has not finished being scanning in this long. Time is in seconds by default, or may be followed by a suffix of 'ms' for milliseconds, 's' for seonds, 'm' for minutes, or 'h' for hours.",
        input: true,
        egInput: "1s; 4m; 2h",
    },
    {
        des: "Max Probe Timeout --- [ --max-rtt-timeout ]",
        value: "--max-rtt-timeout",
        tooltip: "Wait no longer than this for a probe response before giving up or retransmitting the probe. Time is in seconds by default, or may be followed by a suffix of 'ms for millseconds,  's' for seonds, 'm' for minutes, or 'h' for hours.",
        input: true,
        egInput: "1s; 4m; 2h",
    },
    {
        des: "Min Probe Timeout --- [ --min-rtt-timeout ]",
        value: "--min-rtt-timeout",
        tooltip: "Provide a port number and Nmap will send packets from that port where possible.",
        input: true,
        egInput: "1s; 4m; 2h",
    },
    {
        des: "Initial Probe Timeout --- [ --initial-rtt-timeout ]",
        value: "--initial-rtt-timeout",
        tooltip: "Use the time given as the inital estimate of round-trip time. This can speed up scans if you know a good time for the network you're scanning.",
        input: false,
        egInput: null,
    },
    {
        des: "Max Scan Delay [ --max-scan-delay ]",
        value: "--max-scan-delay",
        tooltip: "Tells Nmap what interface to send and receive packet on.",
        input: true,
        egInput: "20",
    },
    {
        des: "Min Delay Between Probes [ --scan-delay ]",
        value: "--scan-delay",
        tooltip: "ells Nmap what interface to send and receive packet on.",
        input: true,
        egInput: "4s; 2m",
    },
]

export const Others = [
    {
        des: "Set IPv4 Time to Live (TTL) --- [ --ttl ]",
        value: "--ttl",
        tooltip: "Set the IPv4 time-to-live field in sent packets to the give value.",
        input: true,
        egInput: "1s; 2m; 4h",
    },
    {
        des: "Fragment IP Packets --- [ -f ]",
        value: "-f",
        tooltip: "Causes the requested scan )including ping scans) to split up TCP headers over serveral packets.",
        input: false,
        egInput: null,
    },
    {
        des: "Verbosity Level --- [ -v ]",
        value: "-v",
        tooltip: "Print more information about the scan in progress. Open ports are shown as they are found as well as completion time estimates.",
        input: false,
        egInput: null,
    },
    {
        des: "Trace Routes to Targets --- [ --traceroute ]",
        value: "--traceroute",
        tooltip: "Trace the network path to each target after scanning. This works with all scan types except connect scan (-sT) and idle scan (-sI).",
        input: false,
        egInput: null,
    },
] 